
BLENDER="C:\Program Files\Blender Foundation\Blender 4.2.1\blender.exe"
DIST=../dist

all : \
    $(DIST)/maze.pnct \
    $(DIST)/maze.scene \

$(DIST)/maze.scene : maze.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "maze.blend:Collection" "$(DIST)/maze.scene"

$(DIST)/maze.pnct : maze.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "maze.blend:Collection" "$(DIST)/maze.pnct" 
